version: "3.1"
services:
  stormy_nginx_subs:
    restart: always
    image: nginx
    command: /bin/bash -c "nginx -g 'daemon off;'"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
      - "./www:/www/pages.charlesreid1.com/htdocs:ro"
        #      - "/www/pages.charlesreid1.com/htdocs:/www/pages.charlesreid1.com/htdocs:ro"
        #      - "/www/hooks.charlesreid1.com/htdocs:/www/hooks.charlesreid1.com/htdocs:ro"
        #      - "/www/bots.charlesreid1.com/htdocs:/www/bots.charlesreid1.com/htdocs:ro"
    ports:
      - "10.5.0.2:7777:7777"
      - "10.5.0.2:7778:7778"
      - "10.5.0.2:7779:7779"

# https://docs.docker.com/compose/compose-file/#network_mode
