site_name: d-nginx-subdomains
site_url: https://pages.charlesreid1.com/d-nginx-subdomains
repo_name: d-nginx-subdomains
repo_url: https://git.charlesreid1.com/docker/d-nginx-subdomains
edit_uri: ""

copyright: 'Copyright &copy; 2018 <a href="https://charlesreid1.com">Charles Reid</a>, released under the <a href="https://opensource.org/licenses/MIT">MIT license</a>'

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'light green'
    accent: 'light green'
  logo:
    icon: 'input'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
nav:
  - 'Home':         'index.md'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true


strict: true
