####################
#
# charlesreid1.blue
# http
# 80
# 
# basically, just redirects to https
#
####################

server {

    user www-data:www-data;

    # http://charlesreid1.blue --> https://charlesreid1.blue

    listen 80;
    listen [::]:80;

    server_name charlesreid1.blue;

    ### location /.well-known {
    ###     allow all;
    ###     root /var/www/letsencrypt/;
    ### }

    location / {
        return 301 https://$server_name$request_uri;
    }

}

server {

    user www-data:www-data;

    # http://www.charlesreid1.blue --> https://charlesreid1.blue

    listen 80;
    listen [::]:80;

    server_name www.charlesreid1.blue;

    location / {
        return 301 https://charlesreid1.blue$request_uri;
    }
}

server {

    user www-data:www-data;

    # http://git.charlesreid1.blue --> https://git.charlesreid1.blue

    listen 80;

    server_name git.charlesreid1.blue;

    location / {
        return 301 https://git.charlesreid1.blue$request_uri;
    }
}

